### ISSUE TITLE
Pacifies Wither Skeletons In Nether

### ISSUE THREAD

**Issue by JLUsr** [Linguardium/DimensionMutability#3]
Wither Skeletons won't aggro at Players or Piglins even when attacked when [dimute-0.1.4.jar](https://www.curseforge.com/minecraft/mc-mods/dimension-mutability/files/4358809) is present. This issue does not occur when a Wither Skeleton is in the overworld.

**Comment by Linguardium** [comment]
it shouldnt even touch them, can you verify that this happens _only_ with dimute, fabric, and a datapack dimension?

**Comment by Linguardium** [comment]
Tested, found issue, working on a fix

**Comment by Linguardium** [comment]
should be fixed by cb03182
